### PR TITLE
docs: move img directory into docs directory

### PR DESCRIPTION
**Pull request by helenakallekleiv**
### What?
Move `img` directory into `docs` directory.

### Why?
When running `mkdocs serve` to preview the site, this warning is presented:

```terminal
WARNING  -  Documentation file 'best-practices.md' contains a link to 'img/hidden-resources.png' which is not
            found in the documentation files.
```
The preview looks like this:
bilde

This is due to `img` dir is located outside of the `docs` dir. A similar issue and solution can be found in this [discussion](https://github.com/squidfunk/mkdocs-material/discussions/3424#discussioncomment-1906860).

### CODE REVIEW

**Review by hknutsen — DISMISSED** [review]
Ran `mkdocs serve` locally and images now show as expected 🎉 

I did however notice that image `module-to-resource-mapping.png` is unused, so we could remove that while we're at it.

Feel free to make that change or merge ✅

**Comment by helenakallekleiv** [comment]
> Ran `mkdocs serve` locally and images now show as expected 🎉
> 
> I did however notice that image `module-to-resource-mapping.png` is unused, so we could remove that while we're at it.
> 
> Feel free to make that change or merge ✅

I see the same thing, I'll remove it 👍🏼

**Review by hknutsen — APPROVED** [review]
Looks good 🦖

**Comment by helenakallekleiv** [comment]
@equinor/terraform-baseline Need 2 approved reviews, anyone? 🙏🏼

**Review by kov117 — APPROVED** [review]

**Pull request merged**
